INSERT INTO "C##WG".APPROVAL_LINE
(APP_LINE_NO, APPROVAL, BOOKMARK)
VALUES(0, '', '');

INSERT INTO "C##WG".APPROVAL_DOCUMENT
(APP_DOC_NO, APP_DOC_ST, APP_DOC_REG_DT, APP_DOC_TITLE, REF_EMP_NO, APP_DOC_CONTENT, APP_LINE_NO, APP_FILE_NO, EMP_NO, FORM_NO)
VALUES(0, '', '', '', '', '', 0, 0, 0, 0);

INSERT INTO "C##WG".APPROVAL_FILE
(APP_FILE_NO, APP_FILE_NM, APP_FILE_SAVE_NM, APP_FILE_SIZE)
VALUES(0, '', '', 0);

INSERT INTO "C##WG".NOTIFICATION
(NOTIFICATION_NO, NOTIFICATION_CHK, APP_DOC_NO)
VALUES(0, '', 0);

--결재문서함 selectAll
SELECT a.APP_DOC_NO, a.APP_DOC_ST, TO_CHAR(a.APP_DOC_REG_DT, 'YYYY-MM-DD HH24:MM') APP_DOC_REG_DT, a.APP_DOC_TITLE, a.EMP_NO, f.FORM_NM
FROM APPROVAL_DOCUMENT a, FORM f WHERE a.FORM_NO = f.FORM_NO;

--문서상세 selectOne
SELECT a.APP_DOC_NO, a.APP_DOC_ST, TO_CHAR(a.APP_DOC_REG_DT, 'YYYY-MM-DD HH24:MM') APP_DOC_REG_DT, a.APP_DOC_TITLE, a.EMP_NO, f.FORM_NM
FROM APPROVAL_DOCUMENT a, FORM f WHERE a.FORM_NO = f.FORM_NO;

--기안하기 selectEMP
SELECT EMP_NO, EMP_NM, PW, EMAIL, PHOTO, ADDRESS, TEL, HIREDATE, WORK_ST, POSITION_NO, DEPT_NO
FROM "C##WG".EMP;
