SELECT * FROM APPROVAL_DOCUMENT ad ;

INSERT INTO "C##WG".APPROVAL_DOCUMENT
(APP_DOC_NO, APP_DOC_ST, APP_DOC_REG_DT, APP_DOC_TITLE, REF_EMP_NO, APP_DOC_CONTENT, APP_LINE_NO, APP_FILE_NO, EMP_NO, FORM_NO)
VALUES(20, '완료', sysdate, '기안을 해볼게', '1,2,3,4,5,6', '내가 기안서를 작성해 볼게!', 2, null, 1, 3);

SELECT * FROM EMP e 

CREATE SEQUENCE sign_seq;
