--sequence 추가
--알림
CREATE SEQUENCE NOTIFICATION_SEQ START WITH 1 INCREMENT BY 1;
--전자결재
CREATE SEQUENCE APP_DOC_SEQ START WITH 1 INCREMENT BY 1;
--결재라인
CREATE SEQUENCE APP_LINE_SEQ START WITH 1 INCREMENT BY 1;
--결재첨부파일
CREATE SEQUENCE APP_FILE_SEQ START WITH 1 INCREMENT BY 1;
--근태
CREATE SEQUENCE ATTENDANCE_SEQ START WITH 1 INCREMENT BY 1;
--양식
CREATE SEQUENCE FORM_SEQ START WITH 1 INCREMENT BY 1;
--양식분류
CREATE SEQUENCE FORM_CLASS_SEQ START WITH 1 INCREMENT BY 1;
--업부일지
CREATE SEQUENCE WORKLOG_SEQ START WITH 1 INCREMENT BY 1;
--채팅방
CREATE SEQUENCE CHAT_ROOM_SEQ START WITH 1 INCREMENT BY 1;
--채팅메시지
CREATE SEQUENCE CHAT_MESSAGE_SEQ START WITH 1 INCREMENT BY 1;
--채팅멤버
CREATE SEQUENCE CHAT_MEMBER_SEQ START WITH 1 INCREMENT BY 1;
--공지사항
CREATE SEQUENCE NOTICE_NO_SEQ START WITH 1 INCREMENT BY 1;
--공지사항 파일
CREATE SEQUENCE NOTICE_FILE_NO_SEQ START WITH 1 INCREMENT BY 1;
--일정
CREATE SEQUENCE SCHEDULE_NO_SEQ START WITH 1 INCREMENT BY 1;
--일정공유
CREATE SEQUENCE SHARED_SCHEDULE_NO_SEQ START WITH 1 INCREMENT BY 1;
--연차
CREATE SEQUENCE USED_ANNUAL_NO_SEQ START WITH 1 INCREMENT BY 1;
--사원
--CREATE SEQUENCE EMP_SEQ START WITH 1 INCREMENT BY 1;
--부서
CREATE SEQUENCE DEPT_NO_SEQ START WITH 1 INCREMENT BY 1;
--부서히스토리
CREATE SEQUENCE HIS_SEQ START WITH 10 INCREMENT BY 10;
--예약
CREATE SEQUENCE RES_SEQ START WITH 1 INCREMENT BY 1;
--사인
CREATE SEQUENCE SIGN_SEQ START WITH 1 INCREMENT BY 1;
