SELECT * FROM WORK_RECORD;

SELECT EMP_NO, JSON_VALUE(WORK_LOG,'$.WORK_LOG.ST') AS ST
FROM WORK_RECORD wr 
WHERE JSON_VALUE(WORK_LOG, '$.WORK_LOG."DATE"') = '2021-10-01';

SELECT * FROM APPROVAL_LINE al;

UPDATE WORK_RECORD SET WORK_LOG = '{"WORK_LOG":[{"EMPNO":"1", "DATE":"2021-10-01", "ST":"08:59:00", "ED":"17:59:34"}]}'
WHERE EMP_NO = 1;

UPDATE WORK_RECORD SET WORK_LOG = '{"WORK_LOG":[{"EMPNO":"2", "DATE":"2021-10-01", "ST":"08:58:00", "ED":"17:59:34"}]}'
WHERE EMP_NO = 2;


SELECT F.FORM_NO, F.FORM_NM, F.FORM_REG_DT, FC.FORM_CLASS_NM 
		FROM FORM f JOIN FORM_CLASSIFICATION fc 
		ON F.FORM_CLASS_NO = FC.FORM_CLASS_NO
		WHERE LOWER(F.FORM_NM) LIKE LOWER('%서%');