INSERT INTO "C##WG".APPROVAL_DOCUMENT
(APP_DOC_NO, APP_DOC_ST, APP_DOC_REG_DT, APP_DOC_TITLE, REF_EMP_NO, APP_DOC_CONTENT, APP_LINE_NO, APP_FILE_NO, EMP_NO, FORM_NO)
VALUES(18, '완료', sysdate, '안녕2', '1', '1', 1, null, 1, 4);

SELECT * FROM APPROVAL_DOCUMENT ad 