--시퀀스 삭제
DROP SEQUENCE EMP_SEQ;

--시퀀스 생성
CREATE SEQUENCE EMP_SEQ 
START WITH 1 
INCREMENT BY 1;

SELECT EMP_SEQ.NEXTVAL FROM DUAL;

--DROP하고 CREATE하는 메소드 같이 실행하기

 INSERT INTO SS(EMP_TEST) 
VALUES (TO_CHAR(SYSDATE,'YYYYMM') || LPAD(EMP_TEST_SEQ.NEXTVAL,2,0));

SELECT TO_CHAR(SYSDATE,'YYYYMM') || LPAD(EMP_SEQ.NEXTVAL,2,0) FROM DUAL;

INSERT INTO SS(EMP_TEST)
   VALUES(20211107);
SELECT * FROM SS;

DELETE FROM SS;

--///////////////////////////////////////////////////////////////////////////////////////////
--사원 INSERT, DELFLAG(WORK_ST==퇴직) 
CREATE SEQUENCE EMP_SEQ
START WITH 1 
INCREMENT BY 1
MINVALUE 1
MAXVALUE 30
CYCLE;

DELETE FROM EMP e ;

INSERT INTO WG.EMP
      (EMP_NO, EMP_NM, PW, 
      EMAIL, PHOTO, ADDRESS, 
      TEL, HIREDATE, WORK_ST, 
      RANK_NO, DEPT_NO)
   VALUES(TO_CHAR(SYSDATE,'YYYYMM') || LPAD(EMP_TEST_SEQ.NEXTVAL,2,0), #{EMP_NM}, #{PW}, 
      #{email}, #{photo}, #{address}, 
      #{tel}, #{hiredate}, #{work_st}, 
      #{rank_no}, #{dept_no});
   
   
INSERT INTO WG.EMP
      (EMP_NO, EMP_NM, PW, 
      EMAIL, PHOTO, ADDRESS, 
      TEL, HIREDATE, WORK_ST, 
      RANK_NO, DEPT_NO)
   VALUES(TO_CHAR(SYSDATE,'YYYYMM') || LPAD(EMP_TEST_SEQ.NEXTVAL,2,0), 'USER', DBMS_RANDOM.STRING('P', 8), 
      'email@email.com', 'testImg', 'testAddress', 
      '010-1234-5678', TO_DATE('2021-12-03','YYYY-MM-DD'), '재직', 
      1, 20);
     
INSERT INTO "C##WG".EMP
		(EMP_NO, EMP_NM, PW, 
		EMAIL, PHOTO, ADDRESS, 
		TEL, HIREDATE, WORK_ST, 
		POSITION_NO, DEPT_NO)
VALUES(TO_CHAR(SYSDATE,'YYYYMM') || LPAD(EMP_TEST_SEQ.NEXTVAL,2,0), 'USER', DBMS_RANDOM.STRING('P', 8), 
      'email@email.com', 'testImg', 'testAddress', 
      '010-1234-5678', TO_DATE('2021-12-03','YYYY-MM-DD'), '재직', 
      1, 20);
     
SELECT * FROM EMP e ;

SELECT EMP_SEQ.NEXTVAL FROM DUAL;
DROP SEQUENCE EMP_SEQ;
CREATE SEQUENCE EMP_SEQ 
		START WITH 1 
		INCREMENT BY 1;

--8자리 영어 대소문자+특수문자 조합 랜덤 생성
SELECT DBMS_RANDOM.STRING('P', 8) PW FROM DUAL; 

   
--사원 전체 조회
SELECT e.EMP_NO,e.EMP_NM ,r.RANK_NM ,d.DEPT_NM
   FROM EMP e, DEPARTMENT d, "RANK" r 
   WHERE e.DEPT_NO=d.DEPT_NO AND e.RANK_NO=r.RANK_NO;


--사원 전체 조회(부서별)
SELECT e.EMP_NO,e.EMP_NM ,r.RANK_NM ,d.DEPT_NM
   FROM EMP e, DEPARTMENT d, "RANK" r 
   WHERE e.DEPT_NO=d.DEPT_NO AND e.RANK_NO=r.RANK_NO
   AND e.DEPT_NO=20;

--사원 전체 조회(이름)
SELECT e.EMP_NO,e.EMP_NM ,r.RANK_NM ,d.DEPT_NM
   FROM EMP e, DEPARTMENT d, "RANK" r 
   WHERE e.DEPT_NO=d.DEPT_NO AND e.RANK_NO=r.RANK_NO
   AND e.EMP_NM='오다원';

--사원 전체 조회(사원번호)
SELECT e.EMP_NO,e.EMP_NM ,r.RANK_NM ,d.DEPT_NM
   FROM EMP e, DEPARTMENT d, "RANK" r 
   WHERE e.DEPT_NO=d.DEPT_NO AND e.RANK_NO=r.RANK_NO
   AND e.EMP_NO=1;

--사원 상세조회
SELECT e.EMP_NO,e.EMP_NM ,e.EMAIL ,e.PHOTO ,e.ADDRESS ,e.TEL ,e.HIREDATE ,r.RANK_NM ,d.DEPT_NM,e.WORK_ST 
   FROM EMP e, DEPARTMENT d, "RANK" r 
   WHERE e.DEPT_NO=d.DEPT_NO AND e.RANK_NO=r.RANK_NO AND EMP_NO =#{emp_no};

--사원 마이페이지
SELECT e.EMP_NO,e.EMP_NM ,e.PW ,e.EMAIL ,e.PHOTO ,e.ADDRESS ,e.TEL ,e.HIREDATE ,e.WORK_ST ,r.RANK_NM ,d.DEPT_NM 
   FROM EMP e, DEPARTMENT d, "RANK" r 
   WHERE e.DEPT_NO=d.DEPT_NO AND e.RANK_NO=r.RANK_NO AND EMP_NO =#{emp_no};

--사원 UPDATE(SELF,ALL)
UPDATE WG.EMP
SET PW='1111', EMAIL='email@email.com', ADDRESS='저멀리 어딘가', TEL='010-1234-5678'
WHERE EMP_NO=1;

UPDATE WG.EMP
SET PW=#{pw}, EMAIL=#{email}, ADDRESS=#{address}, TEL=#{tel}
WHERE EMP_NO=#{emp_no};

--사원 개인정보수정-인사팀
UPDATE WG.EMP
SET EMP_NM='김이름', WORK_ST='휴직', RANK_NO='2', DEPT_NO='10'
WHERE EMP_NO=8;

UPDATE WG.EMP
SET EMP_NM=#{name}, WORK_ST=#{work_st}, RANK_NO=#{rank_no}, DEPT_NO=#{dept_no}
WHERE EMP_NO=#{emp_no};

--비밀번호 확인(마이페이지,비밀번호 변경시)
SELECT PW FROM EMP e WHERE EMP_NO=8;
SELECT * FROM EMP e2 WHERE EMP_NO=20211228 ;
--로그인
SELECT EMP_NO,EMP_NM ,EMAIL ,PHOTO ,RANK_NO ,DEPT_NO 
   FROM EMP e 
   WHERE EMP_NO=20211228 AND PW=1234;

--부서 전체 조회
SELECT DEPT_NO ,DEPT_NM 
   FROM DEPARTMENT d ;

--부서 추가
CREATE SEQUENCE DEPT_NO_SEQ START WITH 10 INCREMENT BY 10;

INSERT INTO DEPARTMENT (DEPT_NO,DEPT_NM) VALUES (DEPT_NO_SEQ.NEXTVAL,'NEW');

SELECT * FROM DEPARTMENT d ;
--부서 수정
UPDATE WG.DEPARTMENT
   SET DEPT_NM='UPDATENEW'
   WHERE DEPT_NO=100;

--예약
CREATE SEQUENCE RES_SEQ START WITH 1 INCREMENT BY 1;

SELECT RES_SEQ.NEXTVAL FROM DUAL;

INSERT INTO WG.RESERVATION
(RES_NO, ROOM_NO, RES_DT, EMP_NO)
VALUES(RES_SEQ.NEXTVAL, 1, TO_DATE(SYSDATE,'YYYY-MM-DD'), 20211228);

SELECT * FROM RESERVATION r;

--예약 조회
SELECT res.RES_NO, r.ROOM_NM , RES_DT
FROM RESERVATION res , ROOM r 
WHERE res.ROOM_NO = r.ROOM_NO ;