INSERT INTO WORKLOG
(WORKLOG_NO, WORKLOG_REG_DT, WORKLOG_MODIFY_DT, WORKLOG_CONTENT, EMP_NO)
VALUES(6, TO_DATE('2021-11-10 03:11:13','YYYY-MM-DD HH24:MI:SS'), '', '신업무일지내용6', 4);
INSERT INTO WORKLOG
(WORKLOG_NO, WORKLOG_REG_DT, WORKLOG_MODIFY_DT, WORKLOG_CONTENT, EMP_NO)
VALUES(7, TO_DATE('2021-11-11 03:11:13','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-11-13 03:11:13','YYYY-MM-DD HH24:MI:SS'), 'SANG업무일지내용7', 4);
INSERT INTO WORKLOG
(WORKLOG_NO, WORKLOG_REG_DT, WORKLOG_MODIFY_DT, WORKLOG_CONTENT, EMP_NO)
VALUES(8, TO_DATE('2021-11-11 03:11:13','YYYY-MM-DD HH24:MI:SS'), '', '김도라업무일지내용8', 4);
INSERT INTO WORKLOG
(WORKLOG_NO, WORKLOG_REG_DT, WORKLOG_MODIFY_DT, WORKLOG_CONTENT, EMP_NO)
VALUES(9, TO_DATE('2021-11-13 03:11:13','YYYY-MM-DD HH24:MI:SS'), '', '김도라업무일지내용9', 5);
INSERT INTO WORKLOG
(WORKLOG_NO, WORKLOG_REG_DT, WORKLOG_MODIFY_DT, WORKLOG_CONTENT, EMP_NO)
VALUES(10, TO_DATE('2021-11-15 03:11:13','YYYY-MM-DD HH24:MI:SS'), '', '스폰지밥업무일지내용10', 6);

SELECT * FROM WORKLOG w 
ORDER BY WORKLOG_NO DESC;


-- 업무일지 검색 - 작성자/내용
SELECT w.*, e.EMP_NM, d.DEPT_NM 
	FROM WORKLOG w 
	LEFT JOIN EMP e 
	ON w.EMP_NO = e.EMP_NO
	LEFT JOIN DEPARTMENT d 
	ON e.DEPT_NO = d.DEPT_NO
	WHERE w.WORKLOG_CONTENT LIKE UPPER('%업무%') 
	OR e.EMP_NM LIKE UPPER('%sang%');

SELECT w.*, e.EMP_NM, d.DEPT_NM 
	FROM WORKLOG w 
	LEFT JOIN EMP e 
	ON w.EMP_NO = e.EMP_NO
	LEFT JOIN DEPARTMENT d 
	ON e.DEPT_NO = d.DEPT_NO
	WHERE UPPER(e.EMP_NM) LIKE UPPER('%sang%')
	OR UPPER(w.WORKLOG_CONTENT) LIKE UPPER('%김%');

SELECT w.*, e.EMP_NM, d.DEPT_NM 
	FROM WORKLOG w 
	LEFT JOIN EMP e 
	ON w.EMP_NO = e.EMP_NO
	LEFT JOIN DEPARTMENT d 
	ON e.DEPT_NO = d.DEPT_NO
	WHERE e.EMP_NM LIKE LOWER('%sang%');

SELECT w.*, e.EMP_NM, d.DEPT_NM 
	FROM WORKLOG w 
	LEFT JOIN EMP e 
	ON w.EMP_NO = e.EMP_NO
	LEFT JOIN DEPARTMENT d 
	ON e.DEPT_NO = d.DEPT_NO
	WHERE w.WORKLOG_CONTENT LIKE UPPER('%김%');
	

	
-- 업무일지 상세조회
SELECT w.*, e.EMP_NM, d.DEPT_NM 
	FROM WORKLOG w 
	LEFT JOIN EMP e 
	ON w.EMP_NO = e.EMP_NO
	LEFT JOIN DEPARTMENT d 
	ON e.DEPT_NO = d.DEPT_NO
	WHERE w.EMP_NO = 1
	ORDER BY w.WORKLOG_NO DESC;

	



