SELECT app_line_no,JSON_VALUE(APPROVAL,'$.APPROVAL[4].EMP_NO') AS id, 
					JSON_VALUE(APPROVAL,'$.APPROVAL[1].APPROVAL_ST') AS chk,
					JSON_VALUE(APPROVAL,'$.APPROVAL[1].REASON') AS regdate, 
					JSON_VALUE(APPROVAL,'$.APPROVAL[1].APPROVAL_DT') AS reason,
					bookmark FROM APPROVAL_LINE al WHERE APP_LINE_NO =1;
					
SELECT * FROM APPROVAL_LINE al;				