CREATE SEQUENCE NOTICE_NO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE NOTICE_FILE_NO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SCHEDULE_NO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SHARED_SCHEDULE_NO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USED_ANNUAL_NO_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO NOTICE
(NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_REG_DT, NOTICE_CHK, EMP_NO, NOTICE_CNT)
VALUES(NOTICE_NO_SEQ.NEXTVAL, 'TITLE', 'CONTENT', SYSDATE, '회사', 3, 0);


INSERT INTO USED_ANNUAL
(USED_ANNUAL_NO, USED_ANNUAL_STARTDAY, USED_ANNUAL_ENDDAY, USED_DAY, EMP_NO)
VALUES(USED_ANNUAL_NO_SEQ.NEXTVAL, '2021-12-20', '2021-12-25', 5, 3);
