--드롭드롭
DROP TABLE CHAT_MESSAGE ;
DROP TABLE CHAT_ROOM ;
DROP TABLE CHAT_MEMBER ;


DROP SEQUENCE CHAT_MEMBER_SEQ;
DROP SEQUENCE CHAT_MESSAGE_SEQ;
DROP SEQUENCE CHAT_ROOM_SEQ;

--채팅멤버
CREATE SEQUENCE CHAT_MEMBER_SEQ START WITH 1 INCREMENT BY 1;
--채팅메시지
CREATE SEQUENCE CHAT_MESSAGE_SEQ START WITH 1 INCREMENT BY 1;
--채팅방
CREATE SEQUENCE CHAT_ROOM_SEQ START WITH 1 INCREMENT BY 1;

/* 채팅방 */
CREATE TABLE CHAT_ROOM (
	CHAT_ROOM_NO NUMBER(16) PRIMARY KEY, /* 채팅방id */
	CHAT_ROOM_NM VARCHAR(255) NOT NULL, /* 채팅방이름 */
	CHAT_ROOM_REG_DT DATE DEFAULT SYSDATE, /* 채팅방 생성시간 */
	CHAT_MEMBERS VARCHAR2(4000) DEFAULT NULL /* 참여자id */
);
--채팅방생성
INSERT INTO CHAT_ROOM
(CHAT_ROOM_NO, CHAT_ROOM_NM)
VALUES(CHAT_ROOM_SEQ.NEXTVAL, 'ㅎㅎ');

--채팅방 이름 변경
UPDATE CHAT_ROOM
SET CHAT_ROOM_NM='룸룸3'
WHERE CHAT_ROOM_NO=3;

--채팅방 참여자 변경
UPDATE CHAT_ROOM
SET CHAT_MEMBERS='1,6,8,11'
WHERE CHAT_ROOM_NO=3;


/* 채팅멤버 */
CREATE TABLE CHAT_MEMBER (
	MEM_NO NUMBER(16) PRIMARY KEY, /* 멤버id */
	CHAT_MEMBER_ST NUMBER(10) DEFAULT 1, /* 채팅방참여상태 */
	CHAT_MEMBER_JOIN_DT DATE DEFAULT SYSDATE, /* 채팅방입장시간 */
	EMP_NO NUMBER(16), /* EMP_NO */
	CONSTRAINTS EMP_NO FOREIGN KEY(EMP_NO) 
	REFERENCES EMP (EMP_NO)
);

--채팅방 생성 후 멤버로 들어감
INSERT INTO CHAT_MEMBER
(MEM_NO, EMP_NO)
VALUES(CHAT_MEMBER_SEQ.NEXTVAL, 5);

--채팅방 삭제 후 참여상태를 2로 변경하여 채팅목록에서 보여주지 않을 예정
UPDATE CHAT_MEMBER 
SET CHAT_MEMBER_ST = 2
WHERE MEM_NO = 6;


/* 채팅메시지  */
CREATE TABLE CHAT_MESSAGE (
	CHAT_MESSAGE_NO NUMBER(16) PRIMARY KEY, /* 채팅메시지id */
	CHAT_MESSAGE_CONTENT VARCHAR2(4000) NOT NULL, /* 채팅메시지내용 */
	CHAT_MESSAGE_REG_DT DATE DEFAULT SYSDATE, /* 채팅메시지보낸시간 */
	MEM_NO NUMBER(16), /* 멤버id */
	CHAT_ROOM_NO NUMBER(16), /* 채팅방id */
	CONSTRAINTS MEM_NO FOREIGN KEY(MEM_NO) 
	REFERENCES CHAT_MEMBER(MEM_NO),
	CONSTRAINTS CHAT_ROOM_NO FOREIGN KEY(CHAT_ROOM_NO) 
	REFERENCES CHAT_ROOM(CHAT_ROOM_NO)
);

INSERT INTO CHAT_MESSAGE
(CHAT_MESSAGE_NO, CHAT_MESSAGE_CONTENT, MEM_NO, CHAT_ROOM_NO)
VALUES(CHAT_MESSAGE_SEQ.NEXTVAL, '', 0, 0);



----------------------------------------------------------
--SELECT 문 테스트
SELECT * FROM CHAT_MESSAGE cm ;
SELECT * FROM CHAT_MEMBER;
SELECT * FROM CHAT_ROOM cr ;
--채팅방

-- 보낸사람 이름/사진/부서/직급 (MEMBER, EMP, DEPARTMENT, POSITION)
SELECT * FROM CHAT_MEMBER cm 
LEFT JOIN EMP e 
ON cm.EMP_NO = e.EMP_NO 
LEFT JOIN DEPARTMENT d 
ON e.DEPT_NO = d.DEPT_NO 
LEFT JOIN "POSITION" p 
ON e.POSITION_NO = p.POSITION_NO 
WHERE cm.MEM_NO = 1;

-- 누가? 메시지 전송 시간, 내용 가져오기, 채팅방 참여자, 채팅방 이름 (MESSAGE, MEMBER, ROOM)
SELECT MESSAGE.*, MEM.*, ROOM.*
	FROM CHAT_MESSAGE MESSAGE
	LEFT JOIN CHAT_MEMBER MEM 
	ON MESSAGE.MEM_NO = MEM.MEM_NO
	LEFT JOIN CHAT_ROOM ROOM 
	ON MESSAGE.CHAT_ROOM_NO = ROOM.CHAT_ROOM_NO 
	WHERE ROOM.CHAT_ROOM_NO = 1 
	ORDER BY MESSAGE.CHAT_MESSAGE_REG_DT DESC ;

--채팅방목록

-- 한 사람이 속해있는 모든 채팅방 목록(MEMBER, EMP, ROOM)
SELECT * FROM CHAT_MEMBER MEM
LEFT JOIN EMP E 
ON MEM.EMP_NO = E.EMP_NO 
LEFT JOIN ROOM R 
ON MEM.

SELECT MESSAGE.*, MEM.*, ROOM.*, E.*
	FROM CHAT_MESSAGE MESSAGE
	LEFT JOIN CHAT_MEMBER MEM 
	ON MESSAGE.MEM_NO = MEM.MEM_NO
	LEFT JOIN EMP E 
	ON MEM.EMP_NO = E.EMP_NO 
	LEFT JOIN CHAT_ROOM ROOM 
	ON MESSAGE.CHAT_ROOM_NO = ROOM.CHAT_ROOM_NO 
	WHERE E.EMP_NO = 2
	ORDER BY MESSAGE.CHAT_MESSAGE_REG_DT DESC ;



-- 채팅방 이름, 가장 최근의 메시지 내용
SELECT * FROM CHAT_MESSAGE 
	WHERE CHAT_MESSAGE_NO = 
	(SELECT MAX(CHAT_MESSAGE_NO) FROM CHAT_MESSAGE WHERE CHAT_ROOM_NO  = 3);


-- 채팅 사원목록
--이건 디비에서 셀렉트 해오는 게 아니라 세션에서 로그인한 사람들의 정보를 받아서 출력해줘야함

--사원목록에서 채팅할 사람을 고르면 채팅방 테이블에 채팅방이 추가되는 동시에 채팅하는 사람이 채팅멤버 테이블에 추가되어야함
--(트랜잭션...? 처리..?)

--사용자가 새로고침을 하지 않더라도 실시간으로 변경되어야하는데 우짤겨,,?
